#!/usr/bin/env bash
# A script that displays as tring indefinitely and catches a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true; do
   echo "To infinity and beyond"
   sleep 2
done
